name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file dockerfiles/php-fpm/Dockerfile --tag chat-anti-bot-image:$(date +%s)
