name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Build the docker-compose stack
      run: docker-compose -f docker-compose.yml build
#    - name: Check running containers
#      run: docker ps -a
#    - name: Check logs
#      run: docker logs backend
#    - name: Run test suite
#      run: docker exec backend pytest --skip-auth
#    - name: Build the Docker image
#      run: docker build . --file dockerfiles/php-fpm/Dockerfile --tag chat-anti-bot-image:$(date +%s)
